// Import Database Models
const db = require('../models');

// Syncing sequelize models 
db.sequelize.sync().then(function () {
    db.Professional.bulkCreate([
    {prof_firstName: 'Vincent', prof_lastName: 'Marco', profession: 'Neurosurgeon', workplace: 'Arlington Memorial Hospital', languages: 'English, Italian', address: '2845 Charmaine Lane, Amarillo, TX 79101', fac_phone: '427-983-9872', gender: 'Male', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Lindsey', prof_lastName: 'Eaton', profession: 'Dentist', workplace: 'WideSmile', languages: 'English', address: '1365 New York Avenue, Fort Worth, TX 76110', fac_phone: '512-555-0175', gender: 'Female', healthcare: 'Maxim Physician Resources'},
    {prof_firstName: 'Thomas', prof_lastName: 'Barley', profession: 'Surgeon', workplace: 'Medical City Arlington', languages: 'English, German', address: '79 Kirkland Circle, Amarillo, TX 79106', fac_phone: '862-943-2625', gender: 'Male', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Diego', prof_lastName: 'Rivetti', profession: 'Psychiatrist', workplace: 'Cardinal Glenon', languages: 'English, Italian, French', address: '7263 Cactus Ave., Garland, TX 75043', fac_phone: '731-560-6934', gender: 'Male', healthcare: 'Maxim Physician Resources'},
    {prof_firstName: 'Jesus', prof_lastName: 'Zavala', profession: 'Radiographer', workplace: 'Hellen Emergency Center', languages: 'English, Spanish', address: '9091 Fawn Lane, Mcallen, TX 78501', fac_phone: '712-907-4877', gender: 'Male', healthcare: 'Anthelio Healthcare Inc.'},
    {prof_firstName: 'Emily', prof_lastName: 'Eaton', profession: 'Sonographer', workplace: 'Umbredge Hospital', languages: 'English', address: '7542 County Rd. Forney, TX 75126', fac_phone: '847-902-4064', gender: 'Female', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Kaydi', prof_lastName: 'Fowler', profession: 'Nurse Practicioner', workplace: 'St.Lewis', languages: 'English', address: '736 South Bridgeton Lane, San Angelo, TX 76901', fac_phone: '435-729-7842', gender: 'Female', healthcare: 'Access Healthcare Inc'},
    {prof_firstName: 'Scott', prof_lastName: 'Miller', profession: 'Orthadonist', workplace: 'Waller Wentrow Hospital', languages: 'English', address: '828 Pierce Lane, San Angelo, TX 76901', fac_phone: '534-214-3100', gender: 'Male', healthcare: 'Anthelio Healthcare Inc.'},
    {prof_firstName: 'Nikkia', prof_lastName: 'Hickman', profession: 'Chiropractor', workplace: 'Xavier Chiropractal', languages: 'English, Italian', address: '8 10th Drive, Helotes, TX 78023', fac_phone: '252-485-1934', gender: 'Female', healthcare: 'Interim HealthCare'},
    {prof_firstName: 'Henry', prof_lastName: 'Newman', profession: 'Orthopedic Surgeon', workplace: 'St.Jude Memorial Hospital', languages: 'English', address: '8283 West Hillside Lane, Victoria, TX 77904', fac_phone: '260-493-3107', gender: 'Male', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Oliver', prof_lastName: 'DuPrince', profession: 'Anesthesiologist', workplace: 'Richardson County Hospital', languages: 'English, French', address: '699 Miller St., Forney, TX 75126', fac_phone: '478-655-3387', gender: 'Male', healthcare: 'Maxim Physician Resources'},
    {prof_firstName: 'Brent', prof_lastName: 'Matello', profession: 'Audiologist', workplace: 'Sainte Paul Emergency Center', languages: 'English, Spanish, Portuguese', address: '8002 Lakewood Ave., Fort Worth, TX 76110', fac_phone: '385-465-9615', gender: 'Male', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Ezekiel', prof_lastName: 'Stout', profession: 'Doctor', workplace: 'Barnes Jewish Hospital', languages: 'English', address: '51 Somerset Ave., Houston, TX 77016', fac_phone: '713-480-0405', gender: 'Male', healthcare: 'Access Healthcare Inc'},
    {prof_firstName: 'Cora', prof_lastName: 'Martin', profession: 'Endoscopy Nurse', workplace: 'Gregor Healthcare', languages: 'English', address: '2 Ryan St., Copperas Cove, TX 76522', fac_phone: '984-896-9387', gender: 'Female', healthcare: 'Access Healthcare Inc'},
    {prof_firstName: 'Alissa', prof_lastName: 'Teilman', profession: 'Nurse Midwife', workplace: 'Sinclare Skincare Treatment Center', languages: 'English', address: '53 Devon Ave., Euless, TX 76039', fac_phone: '801-905-0034', gender: 'Female', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Nathan', prof_lastName: 'Yttrebren', profession: 'Nurse', workplace: 'Elton Emergency Treatment Center', languages: 'English, Russian', address: '31 Trenton Drive, Longview, TX 75604', fac_phone: '405-405-0430', gender: 'Male', healthcare: 'Maxim Physician Resources'},
    {prof_firstName: 'Carlos', prof_lastName: 'Elizondo', profession: 'Nurse Anesthetist', workplace: 'St.Vincent Memorial Hospital', languages: 'English, Spanish', address: '41 Devonshire Street, Longview, TX 75604', fac_phone: '281-978-2662', gender: 'Male', healthcare: 'Anthelio Healthcare Inc.'},
    {prof_firstName: 'Kayla', prof_lastName: 'Fellows', profession: 'Optometrist', workplace: 'Baylor University Medical Center', languages: 'English', address: '735 Fieldstone St., Harlingen, TX 78552', fac_phone: '872-413-4154', gender: 'Female', healthcare: 'Cornerstone Healthcare Group'},
    {prof_firstName: 'Russell', prof_lastName: 'Byrd', profession: 'Pediatric Nurse', workplace: 'Huguley Memorial Medical Center', languages: 'English, German', address: '85 Hall St., Sugar Land, TX 77478', fac_phone: '347-953-2623', gender: 'Male', healthcare: 'Interim HealthCare'},
    {prof_firstName: 'Khalee', prof_lastName: 'Barton', profession: 'Prosthetist', workplace: 'Mercy Hospital', languages: 'English, Swedish', address: '518 Big Rock Cove St., Sugar Land, TX 77478', fac_phone: '386-490-7269', gender: 'Female', healthcare: 'Cornerstone Healthcare Group'},
    {prof_firstName: 'Kathrine', prof_lastName: 'Malkowski', profession: 'Physician', workplace: 'John Peter Smith Hospital', languages: 'English, Hebrew', address: '88 School Ave., Corpus Christi, TX 78418', fac_phone: '458-327-4656', gender: 'Female', healthcare: 'Interim HealthCare'},
    {prof_firstName: 'Cara', prof_lastName: 'Martin', profession: 'Psychiatric Nurse', workplace: 'Northwest Hospital', languages: 'English', address: '8427 Cardinal Drive, Helotes, TX 78023', fac_phone: '859-482-3852', gender: 'Female', healthcare: 'Anthelio Healthcare Inc.'},
    {prof_firstName: 'Russell', prof_lastName: 'Wayne', profession: 'Therapist', workplace: 'Methodist McKinney Hospital', languages: 'English, Italian', address: '8949 Devon Rd., Longview, TX 75604', fac_phone: '518-813-9875', gender: 'Male', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Edward', prof_lastName: 'Yelton', profession: 'Veterinarian', workplace: 'Baylor Heart Hospital', languages: 'English', address: '917 South Williams Ave., Desoto, TX 75115', fac_phone: '385-475-3145', gender: 'Male', healthcare: 'Access Healthcare Inc'},
    {prof_firstName: 'Zachary', prof_lastName: 'Steiner', profession: 'Pediatric Endocrinology Nurse', workplace: 'Medical Center of Plano', languages: 'English, Italian', address: '7439 E. Eagle Court, El Paso, TX 79930', fac_phone: '339-763-3367', gender: 'Male', healthcare: 'Cornerstone Healthcare Group'},
    {prof_firstName: 'Brett', prof_lastName: 'Houle', profession: 'Paramedic', workplace: 'Atlanta Memorial', languages: 'English', address: '82 N. Wagon Street, Helotes, TX 78023', fac_phone: '845-608-7322', gender: 'Male', healthcare: 'Access Healthcare Inc'},
    {prof_firstName: 'Gage', prof_lastName: 'Regamey', profession: 'Oncology Nurse', workplace: 'Marshall Regional Medical Center', languages: 'English, Italian', address: '33 Harvard Lane, Copperas Cove, TX 76522', fac_phone: '301-391-9505', gender: 'Male', healthcare: 'Maxim Physician Resources'},
    {prof_firstName: 'Aela', prof_lastName: 'Welton', profession: 'Occupational Therapist', workplace: 'Paris Regional Medical Center', languages: 'English', address: '749 Lees Creek Lane, Garland, TX 75043', fac_phone: '270-541-4418', gender: 'Female', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Jasmin', prof_lastName: 'Ruiz', profession: 'Occupational Health and Safety Specialist', workplace: 'Bayside Community Hospital', languages: 'English, Italian', address: '9 Canterbury Lane, Forney, TX 75126', fac_phone: '662-822-4032', gender: 'Female', healthcare: 'Cornerstone Healthcare Group'},
    {prof_firstName: 'Karli', prof_lastName: 'Fowler', profession: 'Licensed Vocational Nurse', workplace: 'San Jacinto Methodist Hospital', languages: 'English', address: '852 NW. Cross St., Helotes, TX 78023', fac_phone: '424-223-2860', gender: 'Female', healthcare: 'Anthelio Healthcare Inc.'},
    {prof_firstName: 'Owen', prof_lastName: 'Uradez', profession: 'Licensed Practical Nurse', workplace: 'Dubuis Hospital of Beaumont', languages: 'English, Italian', address: '57 Cherry Hill Street, Desoto, TX 75115', fac_phone: '858-554-7482', gender: 'Male', healthcare: 'Tenet Healthcare Corporation'},
    {prof_firstName: 'Carly', prof_lastName: 'Vinte', profession: 'Intensive Care Nurse', workplace: 'St. Joseph Regional Health Center', languages: 'English', address: '5 Bridge Dr., Fort Worth, TX 76110', fac_phone: '469-303-4345', gender: 'Female', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Daniel', prof_lastName: 'Stout', profession: 'Dialysis Nurse', workplace: 'Baylor Scott & White Medical Center', languages: 'English, Italian', address: '28 South Spring St., Sugar Land, TX 77478', fac_phone: '740-428-5029', gender: 'Male', healthcare: 'Tenet Healthcare Corporation'},
    {prof_firstName: 'Brianna', prof_lastName: 'Stout', profession: 'Flight Nurse', workplace: 'Baylor Scott & White Medical Center', languages: 'English', address: '28 South Spring St., Sugar Land, TX 77478', fac_phone: '240-674-6171', gender: 'Female', healthcare: 'Maxim Physician Resources'},
    {prof_firstName: 'Bert', prof_lastName: 'Cuccatti', profession: 'Cardiovascular Technologist', workplace: 'Conroe Regional Medical Center', languages: 'English, Italian', address: '504 Edinburgh Lane, Coppell, TX 75019', fac_phone: '508-503-5713', gender: 'Male', healthcare: 'Tenet Healthcare Corporation'},
    {prof_firstName: 'Eden', prof_lastName: 'Harvell', profession: 'Ambulatory Nurse', workplace: 'Jennie Sealy Hospital', languages: 'English', address: '8756 Old 53rd Dr., El Paso, TX 79930', fac_phone: '985-283-1937', gender: 'Female', healthcare: 'Access Healthcare Inc'},
    {prof_firstName: 'Brady', prof_lastName: 'Keller', profession: 'Cardiac Catheterization Lab Nurse', workplace: 'Renaissance Hospital', languages: 'English, Italian', address: '53 River Street, El Paso, TX 79930', fac_phone: '862-612-0028', gender: 'Male', healthcare: 'Maxim Physician Resources'},
    {prof_firstName: 'Paul', prof_lastName: 'Armonet', profession: 'Dermatology Nurse', workplace: 'East Houston Regional Medical Center', languages: 'English', address: '6 Sherwood Court, Euless, TX 76039', fac_phone: '281-308-4842', gender: 'Male', healthcare: 'Anthelio Healthcare Inc.'},
    {prof_firstName: 'Cheyanne', prof_lastName: 'Cash', profession: 'Microbiologist', workplace: 'Baylor St. Luke Medical Center', languages: 'English, Italian', address: '8064 Border Street, Sugar Land, TX 77478', fac_phone: '380-274-4299', gender: 'Female', healthcare: 'Tenet Healthcare Corporation'},
    {prof_firstName: 'Madison', prof_lastName: 'Vickers', profession: 'Medical Surgery Nurse', workplace: 'St. Joseph Medical Center', languages: 'English', address: '7653 Tallwood St., Amarillo, TX 79106', fac_phone: '630-622-4054', gender: 'Female', healthcare: 'Supplemental Health Care'},
    {prof_firstName: 'Allison', prof_lastName: 'Cooke', profession: 'Optician', workplace: 'Christus Jasper Memorial Hospital', languages: 'English, Italian', address: '8930 Hilltop Street, Helotes, TX 78023', fac_phone: '970-403-2181', gender: 'Female', healthcare: 'Maxim Physician Resources'},
    {prof_firstName: 'Trevor', prof_lastName: 'Troba', profession: 'Pharmacist', workplace: 'Dickerson Memorial Hospital', languages: 'English', address: '528 Indian Spring Drive, Longview, TX 75604', fac_phone: '458-263-6138', gender: 'Male', healthcare: 'Maxim Physician Resources'},

    ]).then(function (response) {
        console.log('Data successfully added!')
    }).catch(function (error) {
        console.log('Error', error)
    });
});